#cache: pip

language: python

include:
    - name: "Python 3.5.0 on Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.5.0 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.5.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

python:
  - "3.6"

install:
  - pip install coverage

script:
  - coverage run tests/client_tests.py
  - coverage run tests/server_tests.py

branches:
  only:
    - master